# Generated by Django 4.2.3 on 2023-07-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=1024)),
                ('currency', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('scrapped_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapperMemory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('total_scrapped_itme', models.IntegerField(default=0)),
                ('last_scrolled_page', models.IntegerField(default=0)),
                ('last_scrapped_item_number', models.IntegerField(default=0)),
                ('last_scrapped_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.car')),
            ],
            options={
                'verbose_name_plural': 'Scrapper Memory',
            },
        ),
    ]
